name: mjolnir3

channels:
  - conda-forge
  - bioconda

dependencies:
  - cutadapt>=4.6
  - vsearch>=2.27.0
  - swarm>=3.1.4
  - cmake 
  - dnoise>=1.4.1
  - r-base>=4.2
  - r-tidyverse>=2.0
  - bioconductor-biostrings>=2.70.1
  - r-devtools>=2.0
  - r-dplyr>=1.1
  - seqkit>=2.9.0