// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rename_fasta
void rename_fasta(std::string input_file, std::string output_file, std::string prefix);
RcppExport SEXP _mjolnir_rename_fasta(SEXP input_fileSEXP, SEXP output_fileSEXP, SEXP prefixSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type prefix(prefixSEXP);
    rename_fasta(input_file, output_file, prefix);
    return R_NilValue;
END_RCPP
}
// seq2tab
void seq2tab(std::string input_table_file, std::string fasta_file, std::string id_column);
RcppExport SEXP _mjolnir_seq2tab(SEXP input_table_fileSEXP, SEXP fasta_fileSEXP, SEXP id_columnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_table_file(input_table_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type fasta_file(fasta_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type id_column(id_columnSEXP);
    seq2tab(input_table_file, fasta_file, id_column);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mjolnir_rename_fasta", (DL_FUNC) &_mjolnir_rename_fasta, 3},
    {"_mjolnir_seq2tab", (DL_FUNC) &_mjolnir_seq2tab, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mjolnir(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
