# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rename_fasta <- function(input_file, output_file, prefix) {
    invisible(.Call('_mjolnir_rename_fasta', PACKAGE = 'mjolnir', input_file, output_file, prefix))
}

seq2tab <- function(input_table_file, fasta_file, id_column) {
    invisible(.Call('_mjolnir_seq2tab', PACKAGE = 'mjolnir', input_table_file, fasta_file, id_column))
}

